USE OffshoreShiftRosterDB;
GO

IF OBJECT_ID('CCL Offshore Team Shift Roaster', 'U') IS NOT NULL
    DROP TABLE [CCL Offshore Team Shift Roaster];
GO

CREATE TABLE [CCL Offshore Team Shift Roaster] (
    [Date] DATE PRIMARY KEY,
    [Day] VARCHAR(50) NOT NULL,
    [4AM - 1PM           After Business hours] NVARCHAR(500) NULL,
    [1:00 PM - 10:00 PM   Production ] NVARCHAR(500) NULL,
    [7:00PM - 4:00AM Business hours] NVARCHAR(500) NULL,
    [Week off] NVARCHAR(500) NULL,
    [Comments] NVARCHAR(1000) NULL
);
GO

INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-13', 'Monday', N'Gopi', N'Siva (1 - 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-14', 'Tuesday', N'Gopi', N'Siva (1- 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-15', 'Wednesday', N'Akhil', N'Nagesh (3PM - 12AM)/ Gopi (1- 10PM)', N'Suraj', N'Siva', N'Gopi will be assisting Suraj ; Siva is swapping with Nagesh');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-16', 'Thursday', N'Akhil', N'Nagesh (1- 10 PM)', N'Suraj', N'Siva/Gopi', N'Siva I sswapping with Nagesh');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-17', 'Friday', N'Akhil', N'Siva (1- 10 PM)', N'Suraj/Nagesh (10PM -7AM)', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-18', 'Saturday', N'Rohit 7AM - 1PM', N'Siva (1 -10 PM)', N'Akhil (10PM -  7AM)', N'Rohit/Suraj/Nagesh', N'Gopi is using his compoff');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-19', 'Sunday', N'Rohit 7AM - 1PM', N'Siva (1- 10 PM)', N'Akhil (7PM - 4AM)', N'Rohit/Suraj/Nagesh', N'Gopi is using his compoff - Balance 1 compoff remaining');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-20', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-21', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-22', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-23', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-24', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-25', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-26', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-27', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-28', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-29', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-04-30', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-01', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-02', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-03', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-04', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-05', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-06', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-07', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-08', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-09', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-10', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-11', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-12', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-13', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-14', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-15', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', N'Gopi has worked due to sas sync code task.');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-16', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-17', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-19', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-20', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh/Gopi', N'Gopi has utilised his compoff on 20th may; No compoff''s left.');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-21', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-22', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-23', 'Saturday', N'Gopi', N'Akhil; Siva', N'Nagesh', N'Rohit/Suraj/Siva/Akhil', N'siva has swapped with (Akhil, he) will work on Mon ,Tue 1 to 10 PM IST');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-24', 'Sunday', N'Gopi', N'Akhil; Siva', N'Nagesh', N'Rohit/Suraj/Siva/Akhil', N'siva has swapped with (Akhil, he) will work on Mon ,Tue 1 to 10 PM IST');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-25', 'Monday', N'Gopi', N'Siva ; Akhil (1 10 PM)', N'Suraj/Nagesh', N'Siva', N'Akhil doing in place of siva; Akhil has taken weekoff on sat and sun');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-26', 'Tuesday', N'Gopi', N'Siva ; Akhil (1 10 PM)', N'Suraj/Nagesh', N'Siva', N'Akhil doing in place of siva; Akhil has taken weekoff on sat and sun');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-27', 'Wednesday', N'Gopi', N'Gopi (3PM 12);  Akhil (1 10 PM)', N'Suraj/Nagesh', NULL, N'Siva is on leave; Nagesh is working');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-28', 'Thursday', N'Gopi', N'Akhil (1 10 PM)', N'Nagesh', NULL, N'Siva/Suraj is on leave(Bakrid); Gopi and Nagesh are working');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-29', 'Friday', N'Gopi', N'Akhil (1 10 PM)', N'Suraj/Nagesh', NULL, N'Gopi is working in place of siva.(Siva will cover gopi someother day)');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-30', 'Saturday', N'Gopi', N'Akhil (1 10 PM)', N'Nagesh', N'Rohit/Suraj/Siva', N'Nagesh will take weekoff''s on June 1st week');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-05-31', 'Sunday', N'Gopi', N'Akhil (1 10 PM)', N'Nagesh', N'Rohit/Suraj/Siva', N'Nagesh will take weekoff''s on June 1st week');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-01', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-02', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', N'Vasu meeting with Rohit/Suraj : Important');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-03', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-04', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-05', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-06', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-07', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-08', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-09', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-10', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-11', 'Thursday', N'Akhil', N'Gopi (1 10 PM)', N'Suraj', N'Nagesh/Siva', N'Gopi has swapped with Siva');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-12', 'Friday', N'Akhil', N'Gopi (1 10 PM)', N'Suraj/Nagesh', N'Gopi/Siva', N'Gopi has swapped with Siva');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-13', 'Saturday', N'Siva', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Siva will be working in place of gopi');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-14', 'Sunday', N'Siva', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Siva will be working in place of Gopi');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-15', 'Monday', N'Siva/Akhil/Nagesh', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', N'Gopi emergency NA; (Siva/Akhil/Nagesh covered each 3 hours)');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-16', 'Tuesday', N'Siva/Akhil/Nagesh', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', N'Gopi emergency NA; (Siva/Akhil/Nagesh covered each 3 hours)');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-17', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-18', 'Thursday', N'Vasu', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-19', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-20', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-21', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-22', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-23', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-24', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-25', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-26', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-27', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-28', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-29', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-06-30', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-01', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-02', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-03', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-04', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-05', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-06', 'Monday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-07', 'Tuesday', N'Gopi', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Akhil', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-08', 'Wednesday', N'Akhil', N'Gopi (3PM 12)/Siva (1 10PM)', N'Suraj', N'Nagesh', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-09', 'Thursday', N'Akhil', N'Siva (1 10 PM)', N'Suraj', N'Nagesh/Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-10', 'Friday', N'Akhil', N'Siva (1 10 PM)', N'Suraj/Nagesh', N'Gopi', NULL);
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-11', 'Saturday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');
INSERT INTO [CCL Offshore Team Shift Roaster] ([Date], [Day], [4AM - 1PM           After Business hours], [1:00 PM - 10:00 PM   Production ], [7:00PM - 4:00AM Business hours], [Week off], [Comments]) VALUES ('2026-07-12', 'Sunday', N'Gopi', N'Akhil', N'Nagesh', N'Rohit/Suraj/Siva', N'Akhil needs to take care of intern');

GO